#!/usr/bin/env bash
# Installing the nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo mkdir /etc/nginx/html
sudo touch /etc/nginx/html/index.html
sudo echo "Holberton School" > /etc/nginx/html/index.html
sudo printf %s "server {
		listen 80 default_server;
		listen [::]:80 default_server;
		root /etc/nginx/html;
		index index.html index.htm;
	}
	" > /etc/nginx/sites-available/default
sudo service nginx restart
