#!/usr/bin/env bash
# Installing the nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo systemctl start nginx
sudo chown -R ubuntu:ubuntu /var/www/html
echo 'Holberton School' > /var/www/html/index.nginx-debian.html
sudo systemctl restart nginx
