#!/usr/bin/env bash
# 8 is good 4 is bad that's what i check
i=1
while [ $i -le 10 ];
do
	if [ $i -eq 4 ]
	then
		echo bad luck
	elif [ $i -eq 8 ]
	then
		echo good luck
	else
		echo Holberton School
	fi
	((i++))
done
