#!/usr/bin/env bash
# displays the bad luck in the countries around the world
i=1
while [ $i -le 20 ];
do
	case $i in
		4)
			echo $i
			echo bad luck from China
			((i++))
			;;

		9)
			echo $i
			echo bad luck from Japan
			((i++))
			;;

		17)
			echo $i
			echo bad luck from Italy
			((i++))
			;;

		*)
			echo $i
			((i++))
			;;
	esac
done
