#!/usr/bin/env bash
# localhost resolbes to 127.0.0.2 facebook.com resolves to 8.8.8.8
cp /etc/hosts ~/hosts.fr
echo "127.0.0.2		localhost" > ~/hosts.fr
echo "8.8.8.8		facebook.com" >> ~/hosts.fr
cp -f ~/hosts.fr /etc/hosts
