#!/usr/bin/env bash
# localhost resolbes to 127.0.0.2 facebook.com resolves to 8.8.8.8
cp /etc/hosts ~/hosts.fr
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.fr
sed -i '1s/^/8.8.8.8 facebook.com\n/' ~/hosts.fr
cp -f ~/hosts.fr /etc/hosts
