#!/usr/bin/env bash
# Nginx USER
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod -R a+rwx,u-x,g-wx,o-wx /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
